### ISSUE TITLE
More than one AWTRIX

### ISSUE THREAD

**Issue by frittes** [lubeda/awtrix_component#1]
Thanks for the component, works flawless!

Is it possible to extend the component to handle more than one AWTRIX?

Thanks in advance!

**Comment by lubeda** [comment]
Hello frittes updating this component to work with two awtrix is beyond my programming knowledge. 
But if you connect your awtrixes to mqtt you can use this: https://github.com/lubeda/awtrix_python_script
Sorry, there is only a quick and very very dirty german "howto" available.

**Comment by frittes** [comment]
Works fine. Thx!
